name: JWT Auth CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Run Test cases
      run: ./t/run.sh
