name: JWT Auth CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Run Test cases
      run: |
        chmod 777 t/run.sh
        ./t/run.sh
